data:
    dataset: "IMAGENET256"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32
    num_classes: 1000

model:
    model_type: "guided_diffusion"
    is_upsampling: false
    image_size: 256
    in_channels: 3
    model_channels: 256
    out_channels: 6
    num_res_blocks: 2
    attention_resolutions: [8, 16, 32] # [256 // 32, 256 // 16, 256 // 8]
    dropout: 0.0
    channel_mult: [1, 1, 2, 2, 4, 4]
    conv_resample: true
    dims: 2
    num_classes: 1000
    use_checkpoint: false
    use_fp16: true
    num_heads: 4
    num_head_channels: 64
    num_heads_upsample: -1
    use_scale_shift_norm: true
    resblock_updown: true
    use_new_attention_order: false
    var_type: fixedlarge
    ema: false
    ckpt_dir: "checkpoints/imagenet256/256x256_diffusion.pt"

classifier:
    ckpt_dir: "checkpoints/imagenet256/256x256_classifier.pt"
    image_size: 256
    in_channels: 3
    model_channels: 128
    out_channels: 1000
    num_res_blocks: 2
    attention_resolutions: [8, 16, 32] # [256 // 32, 256 // 16, 256 // 8]
    channel_mult: [1, 1, 2, 2, 4, 4]
    use_fp16: true
    num_head_channels: 64
    use_scale_shift_norm: true
    resblock_updown: true
    pool: "attention"

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    total_N: 10000
    batch_size: 100
    last_only: True
    fid_stats_dir: "fid_stats/imagenet256/VIRTUAL_imagenet256_labeled.npz"
    fid_total_samples: 10000
    fid_batch_size: 250
    cond_class: true
    classifier_scale: 2.0
    keep_samples: true
    continuous: false # means whether continue sampling from a number of generated images
    adaptive_tend: true
    time_input_type: "1"
    t_start: 1
    statistics_dir: "dpm_solver_v3/imagenet256_guided/500_1024"
    fid_image_dir: 
    fid_stats_dir: fid_stats/imagenet256/VIRTUAL_imagenet256_labeled.npz # path to FID statistics

fixed_noise: 
    enable: false
    path: fixed_noises/1000_3_256_256.pth # path to a set of fixed noise to decrease the randomness in evaluation

fixed_classes: 
    enable: false
    path: fixed_noises/1000.pth